version: '3'
services: 
  front-end:
    build: 
        context: ./front-end
        dockerfile: dockerfile
    environment: 
        PORT : 3333
    ports:
        - '3000:3000'
  node-server:
    build: 
        context: ./node-server
        dockerfile: dockerfile
    environment: 
        PORT : 3333
    ports: 
        - '3333:3333'